### ISSUE TITLE
Support for attributes

### ISSUE THREAD

**Issue by istudyatuni** [dioxus-community/dioxus-i18n#9]
As title says, [attributes](https://projectfluent.org/fluent/guide/attributes.html) currently not supported

```rs
t!("login-input.placeholder")
```

Or is there an another way to retrieve it?

**Comment by marc2332** [comment]
Interesting! I don't think there is any way to do it atm, would you be willing to investigate and perhaps make a PR? 😄 It's okay to say no too 🦀

**Comment by istudyatuni** [comment]
I can take a look, but no promises :)

**Comment by istudyatuni** [comment]
> I don't think there is any way to do it atm

Why?

**Comment by marc2332** [comment]
> > I don't think there is any way to do it atm
> 
> Why?

I mean dioxus-i18n doesn't support it right now, I just never thought about attributes :)

**Comment by marc2332** [comment]
> I can take a look, but no promises :)

Thanks! Feel free to ask me if you need help or something 🦀

**Comment by istudyatuni** [comment]
I noticed that

> Attributes of terms are private and cannot be retrieved by the localization runtime

so this can be closed I think

**Comment by istudyatuni** [comment]
It works like

```fluent
type =
    .first = 1
    .second = 2

msg = { $ty ->
    [first] First line
    [second] Second line
   *[other] Other: { $ty }
}
```

[Playground](https://projectfluent.org/play/?s=eyJtZXNzYWdlcyI6InR5cGUgPVxuICAgIC5maXJzdCA9IDFcbiAgICAuc2Vjb25kID0gMlxuXG5tc2cgPSB7ICR0eSAtPlxuICAgIFtmaXJzdF0gRmlyc3QgbGluZVxuICAgIFtzZWNvbmRdIFNlY29uZCBsaW5lXG4gICAqW290aGVyXSBPdGhlcjogeyAkdHkgfVxufVxuIiwidmFyaWFibGVzIjp7InR5IjoiZmlyc3QifSwic2V0dXAiOnsidmlzaWJsZSI6WyJtZXNzYWdlcyIsIm91dHB1dCIsImNvbmZpZyJdLCJsb2NhbGUiOiJlbi1VUyIsImRpciI6Imx0ciJ9fQ)

**Comment by marc2332** [comment]
ohh, thanks for digging into this anyway :)
